CREATE TABLE ASSOCIATION(
    idAsso MEDIUMINT NOT NULL AUTO_INCREMENT,
    nomAsso VARCHAR(255) NOT NULL,
    domaineAsso VARCHAR(255) NOT NULL,
    PRIMARY KEY(idAsso)
);


CREATE TABLE EVENEMENT_ORGANISE_PAR_ASSO(
    idAsso MEDIUMINT NOT NULL,
    idEvent MEDIUMINT NOT NULL AUTO_INCREMENT,
    dateEvent DATE NOT NULL,
    lieuEvent VARCHAR(255) NOT NULL,
    descriptionEvent VARCHAR(255) NOT NULL,
    PRIMARY KEY(idEvent),
    FOREIGN KEY(idAsso) REFERENCES ASSOCIATION(idAsso)
);


CREATE TABLE ENTREPRISE(
    idEntreprise MEDIUMINT NOT NULL AUTO_INCREMENT,
    nomEntreprise VARCHAR(255) NOT NULL,
    domaineEntreprise VARCHAR(255) NOT NULL,
    PRIMARY KEY(idEntreprise)
);


CREATE TABLE EVENEMENT_ORGANISE_PAR_ENTREPRISE(
    idEntreprise MEDIUMINT NOT NULL,
    idEvent MEDIUMINT NOT NULL AUTO_INCREMENT,
    dateEvent DATE NOT NULL,
    lieuEvent VARCHAR(255) NOT NULL,
    descriptionEvent VARCHAR(255) NOT NULL,
    PRIMARY KEY(idEvent),
    FOREIGN KEY(idEntreprise) REFERENCES ENTREPRISE(idEntreprise)
);




