CREATE TABLE ASSOCIATION(
    idAsso MEDIUMINT NOT NULL AUTO_INCREMENT,
    nomAsso VARCHAR(255) NOT NULL,
    domaineAsso VARCHAR(255) NOT NULL,
    PRIMARY KEY(idAsso)
);


CREATE TABLE EVENEMENT_ORGANISE_PAR_ASSO(
    idAsso MEDIUMINT NOT NULL,
    idEvent MEDIUMINT NOT NULL AUTO_INCREMENT,
    dateEvent DATE NOT NULL,
    lieuEvent VARCHAR(255) NOT NULL,
    descriptionEvent VARCHAR(255) NOT NULL,
    PRIMARY KEY(idEvent),
    FOREIGN KEY(idAsso) REFERENCES ASSOCIATION(idAsso)
);

