pipeline {
    agent any

    parameters {
        string(name: 'NEW_IP', defaultValue: '', description: 'IP de l’instance EC2')
        string(name: 'PEM_KEY_PATH', defaultValue: '/home/florian-andr/.ssh/ipsa.pem', description: 'Chemin absolu de la clé PEM à utiliser pour la connexion SSH')
    }

    stages {
        stage('Exécuter les scripts update_checker.sh et scraping.sh') {
            steps {
                script {
                    // Script distant mis dans un fichier temporaire
                    writeFile file: 'run_scripts.sh', text: '''
                        echo "==> Lancement du script de vérification de mise à jour"
                        chmod +x /home/ubuntu/projets_groupe/update_check.sh
                        /home/ubuntu/projets_groupe/update_check.sh

                        echo "==> Lancement du script de scraping"
                        chmod +x /home/ubuntu/projets_groupe/scraping.sh
                        /home/ubuntu/projets_groupe/scraping.sh
                    '''.stripIndent()

                    // Transfert et exécution du script
                    sh """
                        sudo -u florian-andr scp -i ${params.PEM_KEY_PATH} run_scripts.sh ubuntu@${params.NEW_IP}:/home/ubuntu/
                        sudo -u florian-andr ssh -i ${params.PEM_KEY_PATH} ubuntu@${params.NEW_IP} 'bash /home/ubuntu/run_scripts.sh'
                    """
                }
            }
        }
    }
}
